import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, Database, Loader2, Play, ScanSearch, Sparkles, UserCheck } from "lucide-react";
import type { AISolutionModule } from "../lib/aiSolutionData";
import { analysisKindFor, analysisMeta, runAnalysis, type AnalysisPeriod, type AnalysisResult, type AnalysisScenario } from "../lib/aiAnalysisData";
import type { Site } from "../lib/siteData";
import { Button } from "./ui/button";
import { ProgressBar, StatusPill } from "./shared";

const phases = ["데이터 수집", "패턴 비교", "위험 계산", "권고 생성"];

function ResultVisual({ result }: { result: AnalysisResult }) {
  if (result.kind === "safety") return <div className="relative h-56 overflow-hidden rounded-xl bg-gradient-to-br from-slate-500 via-slate-300 to-slate-600">
    <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(90deg,transparent 49%,white 50%,transparent 51%),linear-gradient(transparent 49%,white 50%,transparent 51%)", backgroundSize: "52px 52px" }} />
    <div className="absolute left-[12%] top-[22%] h-[42%] w-[28%] border-2 border-red-500 bg-red-500/10"><span className="bg-red-500 px-1.5 py-1 text-[10px] font-bold text-white">통로 적치 91%</span></div>
    <div className="absolute bottom-[12%] right-[14%] h-[25%] w-[34%] border-2 border-amber-400 bg-amber-300/10"><span className="bg-amber-500 px-1.5 py-1 text-[10px] font-bold text-white">미끄럼 위험 86%</span></div>
    <div className="absolute bottom-3 left-3 rounded bg-black/65 px-2 py-1 text-xs text-white"><ScanSearch className="mr-1 inline size-3.5" />AI 위험영역 판독 화면</div>
  </div>;
  if (result.kind === "report") return <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="border-b pb-3"><span className="text-xs font-bold text-[var(--success)]">SAMGU ONE AI REPORT</span><h3 className="mt-1 text-lg font-bold">현장 운영 분석 요약</h3></div><p className="mt-4 text-sm leading-6">{result.summary}</p><div className="mt-4 grid grid-cols-3 gap-2">{result.metrics.map(m => <div key={m.label} className="rounded bg-muted p-2 text-center"><p className="text-[10px] text-muted-foreground">{m.label}</p><b>{m.value}</b></div>)}</div><p className="mt-4 rounded bg-[var(--brand-blue-soft)] p-3 text-xs"><Sparkles className="mr-1 inline size-3.5" />{result.recommendation}</p></div>;
  return <div className="rounded-xl border border-border bg-card p-4"><div className="mb-4 flex items-center justify-between"><b className="text-sm">{analysisMeta[result.kind].iconLabel}</b><span className="text-xs text-muted-foreground">회색선: 비교 기준</span></div><div className="flex h-44 items-end gap-3">{result.series.map(item => <div key={item.label} className="flex h-full flex-1 flex-col justify-end"><div className="relative flex-1"><div className="absolute bottom-0 left-1/2 w-4 -translate-x-[70%] rounded-t bg-muted" style={{ height: `${item.compare ?? 0}%` }} /><div className="absolute bottom-0 left-1/2 w-4 translate-x-[-15%] rounded-t bg-[var(--brand-blue)]" style={{ height: `${Math.min(100, item.value)}%` }} /></div><p className="mt-2 truncate text-center text-[10px] text-muted-foreground">{item.label}</p><b className="text-center text-[10px]">{item.value}</b></div>)}</div></div>;
}

export function AiAnalysisWorkspace({ module, site, onCreateOrder, onClose }: { module: AISolutionModule; site: Site; onCreateOrder: (title: string) => void; onClose: () => void }) {
  const kind = analysisKindFor(module.id)!;
  const meta = analysisMeta[kind];
  const [period, setPeriod] = useState<AnalysisPeriod>("7일");
  const [scenario, setScenario] = useState<AnalysisScenario>("주의");
  const [running, setRunning] = useState(false);
  const [phase, setPhase] = useState(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  useEffect(() => { setResult(null); setPhase(0); setRunning(false); }, [module.id, site.id, period, scenario]);
  const preview = useMemo(() => runAnalysis(kind, site, period, scenario), [kind, site, period, scenario]);
  const run = () => { setRunning(true); setResult(null); setPhase(0); let current = 0; const timer = window.setInterval(() => { current += 1; if (current >= phases.length) { window.clearInterval(timer); setRunning(false); setResult(preview); } else setPhase(current); }, 320); };

  return <section id="ai-analysis-workspace" className="scroll-mt-5 overflow-hidden rounded-[var(--radius)] border-2 border-[var(--brand-blue)]/25 bg-card shadow-lg">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b bg-[var(--brand-blue-soft)]/60 p-5"><div><div className="mb-1 flex items-center gap-2"><Sparkles className="size-5 text-[var(--brand-blue)]" /><span className="text-xs font-bold text-[var(--brand-blue)]">AI 분석 체험 워크스페이스</span></div><h2 className="text-xl font-bold">{meta.title}</h2><p className="mt-1 text-sm text-muted-foreground">{site.name} · 입력 데이터: {meta.input}</p></div><button onClick={onClose} className="rounded-lg border bg-card px-3 py-1.5 text-xs font-semibold">워크스페이스 닫기</button></header>
    <div className="grid gap-5 p-5 xl:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="space-y-4"><div className="rounded-lg border p-4"><p className="mb-3 text-sm font-semibold">분석 조건</p><label className="block text-xs text-muted-foreground">대상 현장<input value={site.name} readOnly className="mt-1 h-9 w-full rounded-lg border bg-muted px-3 text-sm text-foreground" /></label><label className="mt-3 block text-xs text-muted-foreground">분석 기간<select value={period} onChange={e => setPeriod(e.target.value as AnalysisPeriod)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3 text-sm text-foreground">{(["오늘","7일","30일"] as const).map(v => <option key={v}>{v}</option>)}</select></label><label className="mt-3 block text-xs text-muted-foreground">예시 시나리오<select value={scenario} onChange={e => setScenario(e.target.value as AnalysisScenario)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3 text-sm text-foreground">{(["정상","주의","위험"] as const).map(v => <option key={v}>{v}</option>)}</select></label><Button disabled={running} onClick={run} className="mt-4 w-full bg-[var(--brand-navy)]">{running ? <Loader2 className="size-4 animate-spin" /> : <Play className="size-4" />}{running ? "분석 중" : "AI 분석 실행"}</Button></div>
        <div className="rounded-lg bg-muted/60 p-4 text-xs leading-5 text-muted-foreground"><Database className="mb-2 size-4" /><b className="text-foreground">실제형 시제품</b><br />선택 조건과 현장 KPI에 재현 가능한 계산 규칙을 적용합니다. 개인정보와 외부 AI API는 사용하지 않습니다.</div>
      </aside>
      <div className="min-w-0">{running && <div className="grid min-h-[390px] place-items-center rounded-xl border border-dashed"><div className="w-full max-w-md text-center"><Loader2 className="mx-auto mb-4 size-9 animate-spin text-[var(--brand-blue)]" /><p className="font-semibold">{phases[phase]}</p><p className="mt-1 text-xs text-muted-foreground">{phase + 1} / {phases.length} 단계</p><div className="mt-4"><ProgressBar value={(phase + 1) / phases.length * 100} /></div><div className="mt-5 flex justify-between text-[10px] text-muted-foreground">{phases.map((p,i) => <span key={p} className={i <= phase ? "font-bold text-[var(--brand-blue)]" : ""}>{p}</span>)}</div></div></div>}
        {!running && !result && <div className="grid min-h-[390px] place-items-center rounded-xl border border-dashed bg-muted/20 text-center"><div><BarChart3 className="mx-auto mb-3 size-10 text-muted-foreground" /><p className="font-semibold">분석 조건을 선택하고 실행하세요</p><p className="mt-1 text-xs text-muted-foreground">시나리오에 따라 결과 수치와 권고가 달라집니다.</p></div></div>}
        {result && <div><div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-lg border p-3"><p className="text-[11px] text-muted-foreground">AI 판정</p><StatusPill tone={result.label.includes("정상") || result.label.includes("달성") ? "green" : result.label.includes("주의") || result.label.includes("관찰") ? "amber" : "red"}>{result.label}</StatusPill></div><div className="rounded-lg border p-3"><p className="text-[11px] text-muted-foreground">분석 점수</p><b className="text-2xl">{result.score}</b><span className="text-xs text-muted-foreground"> / 100</span></div><div className="rounded-lg border p-3"><p className="text-[11px] text-muted-foreground">신뢰도</p><b className="text-2xl">{result.confidence}%</b></div><div className="rounded-lg border p-3"><p className="text-[11px] text-muted-foreground">분석 상태</p><span className="mt-1 flex items-center gap-1 text-sm font-semibold text-[var(--success)]"><CheckCircle2 className="size-4" />완료</span></div></div><div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><ResultVisual result={result} /><div className="rounded-xl border p-4"><h3 className="font-semibold">분석 결과</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{result.summary}</p><div className="mt-3 grid grid-cols-3 gap-2">{result.metrics.map(m => <div key={m.label} className="rounded bg-muted/60 p-2"><p className="text-[10px] text-muted-foreground">{m.label}</p><b className="text-sm">{m.value}</b></div>)}</div><p className="mt-4 text-xs font-bold">판단 근거</p><div className="mt-2 flex flex-wrap gap-1.5">{result.evidence.map(e => <span key={e} className="rounded bg-muted px-2 py-1 text-[11px]">{e}</span>)}</div><div className="mt-4 rounded-lg bg-[var(--warning-soft)] p-3 text-sm"><AlertTriangle className="mr-1 inline size-4 text-[var(--warning)]" /><b>AI 권고:</b> {result.recommendation}</div><Button onClick={() => onCreateOrder(`[${meta.title}] ${result.recommendation}`)} className="mt-3 w-full bg-[var(--brand-navy)]"><UserCheck className="size-4" />담당자 승인 요청 생성</Button></div></div></div>}
      </div>
    </div>
  </section>;
}
