import { useMemo, useState } from "react";
import { AlertTriangle, Check, Clock3, Headphones, Inbox, Link2, Mail, MessageSquareText, Phone, Send, ShieldCheck, Smartphone, Sparkles, UserCheck } from "lucide-react";
import { toast } from "sonner";
import { readOperations, writeOperations, type MaintenanceOrder, type OperationsState, type VocChannel, type VocStatus, type VocTicket } from "../lib/operationsStore";
import { PageHeader, SectionCard, StatCard, StatusPill } from "./shared";
import { Button } from "./ui/button";

const NOW = new Date("2026-06-20T16:45:00+09:00").getTime();
const channelIcon = { 전화: Phone, 이메일: Mail, 앱: Smartphone, "고객 포털": MessageSquareText };
const statusOrder: VocStatus[] = ["접수", "분석 완료", "담당 배정", "처리 중", "고객 확인", "종료"];
const managers = ["김대영", "박정호", "이현아", "정수진"];
const fmt = (iso: string) => new Date(iso).toLocaleString("ko-KR", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" });
function sla(ticket: VocTicket) { const target = new Date(["접수", "분석 완료"].includes(ticket.status) ? ticket.responseDue : ticket.resolutionDue).getTime(); const min = Math.round((target - NOW) / 60000); return { min, label: min < 0 ? `${Math.abs(min)}분 초과` : min < 60 ? `${min}분 남음` : `${Math.floor(min / 60)}시간 ${min % 60}분`, tone: min < 0 ? "red" as const : min < 60 ? "amber" as const : "green" as const }; }

export function VocSlaView() {
  const [state, setState] = useState<OperationsState>(() => readOperations());
  const [audience, setAudience] = useState<"operations" | "customer">("operations");
  const [selectedId, setSelectedId] = useState(state.vocTickets[0]?.id ?? "");
  const [filter, setFilter] = useState("전체");
  const [createOpen, setCreateOpen] = useState(false);
  const [channel, setChannel] = useState<VocChannel>("고객 포털"); const [client, setClient] = useState("한국스마트물류"); const [site, setSite] = useState("김포 스마트물류센터"); const [content, setContent] = useState("");
  const persist = (next: OperationsState) => { setState(next); writeOperations(next); };
  const tickets = useMemo(() => state.vocTickets.filter(t => filter === "전체" || t.status === filter || t.category === filter || t.urgency === filter), [state.vocTickets, filter]);
  const selected = state.vocTickets.find(t => t.id === selectedId) ?? tickets[0];
  const overdue = state.vocTickets.filter(t => sla(t).min < 0 && t.status !== "종료").length;
  const urgent = state.vocTickets.filter(t => t.urgency === "긴급" && t.status !== "종료").length;
  const repeat = state.vocTickets.filter(t => t.repeated && t.status !== "종료").length;

  const updateTicket = (id: string, patch: Partial<VocTicket>) => persist({ ...state, vocTickets: state.vocTickets.map(t => t.id === id ? { ...t, ...patch } : t) });
  const createTicket = () => {
    if (!content.trim()) return toast.error("접수 내용을 입력하세요.");
    const lower = content.toLowerCase(); const category: VocTicket["category"] = /승강기|고장|냉난방|시설/.test(lower) ? "시설" : /미끄럼|위험|사고/.test(lower) ? "안전" : /청소|쓰레기|미화/.test(lower) ? "미화" : /출근|결근|근태/.test(lower) ? "근태" : "서비스";
    const urgency: VocTicket["urgency"] = /긴급|사고|멈|위험/.test(lower) ? "긴급" : /불편|지연|재발/.test(lower) ? "주의" : "일반";
    const id = `VOC-260620-${String(state.vocTickets.length + 19).padStart(3, "0")}`;
    const received = "2026-06-20T16:45:00+09:00";
    const ticket: VocTicket = { id, channel, client, site, title: content.trim().slice(0, 28), content: content.trim(), category, urgency, sentiment: /감사|좋/.test(lower) ? "긍정" : /불편|문제|위험|지연|고장|멈/.test(lower) ? "부정" : "중립", status: "분석 완료", owner: category === "시설" ? "박정호" : "김대영", receivedAt: received, responseDue: "2026-06-20T17:15:00+09:00", resolutionDue: urgency === "긴급" ? "2026-06-20T20:45:00+09:00" : "2026-06-21T16:45:00+09:00", confidence: 91, repeated: false, evidence: [`${category} 관련 핵심어`, `${urgency} 표현`, `${channel} 접수 문맥`], recommendation: `${category} 담당자에게 배정하고 SLA 내 처리 결과를 회신하세요.` };
    persist({ ...state, vocTickets: [ticket, ...state.vocTickets] }); setSelectedId(id); setContent(""); setCreateOpen(false); toast.success("AI 분류를 완료하고 통합 접수함에 등록했습니다.");
  };
  const assign = () => { if (!selected) return; updateTicket(selected.id, { status: "담당 배정", owner: selected.owner || "김대영" }); toast.success("담당자에게 배정했습니다."); };
  const linkAction = () => {
    if (!selected) return;
    if (selected.category === "시설") {
      const asset = state.assets.find(a => a.site === selected.site) ?? state.assets[0];
      const order: MaintenanceOrder = { id: `order-voc-${Date.now()}`, assetId: asset.id, symptom: `[${selected.id}] ${selected.content}`, risk: selected.urgency === "긴급" ? "높음" : "보통", owner: selected.owner, due: "2026-06-20", cost: 0, status: "대기", createdAt: "2026-06-20" };
      persist({ ...state, orders: [order, ...state.orders], vocTickets: state.vocTickets.map(t => t.id === selected.id ? { ...t, status: "처리 중", linkedModule: "시설·자산 관리", linkedOrderId: order.id } : t) });
    } else updateTicket(selected.id, { status: "처리 중", linkedModule: selected.category === "근태" ? "근태 관리" : "현장 AI 안전·미화", linkedOrderId: `ACTION-${Date.now()}` });
    toast.success("관련 업무 모듈에 작업지시를 생성했습니다.");
  };
  const makeDraft = () => { if (!selected) return; updateTicket(selected.id, { status: "고객 확인", responseDraft: `${selected.client} 담당자님, 접수하신 '${selected.title}' 건을 확인했습니다. ${selected.linkedModule ?? "담당 부서"}에서 조치를 진행했으며 동일 문제가 재발하지 않도록 후속 점검하겠습니다. 불편을 드려 죄송합니다.` }); toast.success("처리 이력을 바탕으로 회신 초안을 작성했습니다."); };
  const approveResponse = () => { if (!selected?.responseDraft) return; updateTicket(selected.id, { status: "종료", responseApprovedBy: "김대영 매니저", responseSentAt: "2026-06-20T16:45:00+09:00" }); toast.success("담당자 승인 후 고객사에 회신했습니다."); };

  return <div>
    <PageHeader title="고객 VOC·SLA 관리" subtitle="멀티채널 고객 요청을 접수하고 AI 분류, 현장 조치, SLA와 고객 회신까지 추적합니다." action={<Button onClick={() => setCreateOpen(v => !v)} className="bg-[var(--brand-navy)]"><Inbox className="size-4" />VOC 접수</Button>} />
    <div className="mb-5 flex gap-1 rounded-lg border bg-card p-1">{[["operations","운영팀 처리 화면"],["customer","고객사 진행 화면"]].map(([key,label]) => <button key={key} onClick={() => setAudience(key as typeof audience)} className={`flex-1 rounded-md px-4 py-2 text-sm font-semibold ${audience === key ? "bg-[var(--brand-navy)] text-white" : "text-muted-foreground"}`}>{label}</button>)}</div>

    {audience === "operations" ? <>
      <div className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard label="진행 VOC" value={state.vocTickets.filter(t => t.status !== "종료").length} unit="건" icon={Inbox} tone="navy" hint="통합 채널" /><StatCard label="SLA 초과" value={overdue} unit="건" icon={Clock3} tone="red" hint="즉시 확인" /><StatCard label="긴급 요청" value={urgent} unit="건" icon={AlertTriangle} tone="amber" hint="4시간 처리 목표" /><StatCard label="반복 민원" value={repeat} unit="건" icon={MessageSquareText} tone="blue" hint="최근 30일" /></div>
      {createOpen && <SectionCard title="신규 VOC 접수·AI 분석" description="전화·이메일·앱·고객 포털 접수를 동일한 구조로 등록합니다." icon={Inbox} className="mb-5"><div className="grid gap-3 lg:grid-cols-[140px_180px_220px_minmax(0,1fr)_110px]"><select value={channel} onChange={e => setChannel(e.target.value as VocChannel)} className="h-10 rounded-lg border bg-card px-2 text-sm">{Object.keys(channelIcon).map(v => <option key={v}>{v}</option>)}</select><input value={client} onChange={e => setClient(e.target.value)} className="h-10 rounded-lg border px-3 text-sm" placeholder="고객사" /><input value={site} onChange={e => setSite(e.target.value)} className="h-10 rounded-lg border px-3 text-sm" placeholder="현장" /><input value={content} onChange={e => setContent(e.target.value)} className="h-10 rounded-lg border px-3 text-sm" placeholder="접수 내용 입력" /><Button onClick={createTicket}><Sparkles className="size-4" />AI 접수</Button></div></SectionCard>}
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.05fr)_minmax(420px,.95fr)]">
        <SectionCard title="통합 VOC 접수함" description="채널과 관계없이 SLA 우선순위로 관리" icon={Headphones} action={<select value={filter} onChange={e => setFilter(e.target.value)} className="h-8 rounded-md border bg-card px-2 text-xs"><option>전체</option><option>긴급</option><option>시설</option><option>안전</option><option>처리 중</option><option>고객 확인</option></select>}><div className="space-y-2">{tickets.map(t => { const Icon = channelIcon[t.channel]; const timer = sla(t); return <button key={t.id} onClick={() => setSelectedId(t.id)} className={`w-full rounded-lg border p-3 text-left ${selected?.id === t.id ? "border-[var(--brand-blue)] bg-[var(--brand-blue-soft)]/40" : "border-border"}`}><div className="flex items-start gap-3"><Icon className="mt-0.5 size-4 text-muted-foreground" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{t.title}</b>{t.urgency === "긴급" && <StatusPill tone="red">긴급</StatusPill>}{t.repeated && <span className="text-[10px] font-semibold text-[var(--warning)]">반복</span>}</div><p className="mt-1 text-xs text-muted-foreground">{t.client} · {t.site} · {t.channel} · {fmt(t.receivedAt)}</p></div><div className="text-right"><StatusPill tone={timer.tone}>{timer.label}</StatusPill><p className="mt-1 text-[10px] text-muted-foreground">{t.status}</p></div></div></button>})}</div></SectionCard>
        {selected && <SectionCard title="AI 분석·처리" description={`${selected.id} · 개인정보 포함 내부 화면`} icon={Sparkles} action={<StatusPill tone={selected.confidence >= 90 ? "green" : "amber"}>신뢰도 {selected.confidence}%</StatusPill>}><div className="border-b pb-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{selected.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{selected.content}</p></div><StatusPill tone={selected.urgency === "긴급" ? "red" : selected.urgency === "주의" ? "amber" : "slate"}>{selected.category} · {selected.urgency}</StatusPill></div></div><div className="grid grid-cols-2 gap-2 py-4 text-xs"><div className="rounded bg-muted/60 p-3"><span className="text-muted-foreground">담당자</span><select value={selected.owner} onChange={e => updateTicket(selected.id, { owner: e.target.value })} className="mt-1 block w-full bg-transparent font-semibold">{managers.map(m => <option key={m}>{m}</option>)}</select></div><div className="rounded bg-muted/60 p-3"><span className="text-muted-foreground">감정 분석</span><b className="mt-1 block">{selected.sentiment} · 반복 {selected.repeated ? "감지" : "없음"}</b></div></div><p className="text-xs font-bold">판단 근거</p><div className="mt-2 flex flex-wrap gap-1.5">{selected.evidence.map(e => <span key={e} className="rounded bg-muted px-2 py-1 text-[11px]">{e}</span>)}</div><div className="mt-4 rounded-lg border-l-4 border-[var(--warning)] bg-[var(--warning-soft)] p-3 text-sm"><b>AI 권고</b><p className="mt-1">{selected.recommendation}</p></div>{selected.linkedModule && <p className="mt-3 flex items-center gap-2 rounded border p-2 text-xs"><Link2 className="size-4 text-[var(--brand-blue)]" /><b>{selected.linkedModule}</b> 작업 {selected.linkedOrderId} 연결됨</p>}{selected.responseDraft && <div className="mt-3 rounded-lg border p-3"><p className="text-xs font-bold">고객 회신 초안</p><p className="mt-2 text-sm leading-6">{selected.responseDraft}</p></div>}<div className="mt-4 flex flex-wrap gap-2">{selected.status === "분석 완료" && <Button size="sm" onClick={assign}><UserCheck className="size-4" />담당 배정</Button>}{["담당 배정","분석 완료"].includes(selected.status) && <Button size="sm" onClick={linkAction}><Link2 className="size-4" />작업지시 생성</Button>}{selected.status === "처리 중" && <Button size="sm" onClick={makeDraft}><Sparkles className="size-4" />회신 초안 생성</Button>}{selected.status === "고객 확인" && selected.responseDraft && !selected.responseSentAt && <Button size="sm" onClick={approveResponse}><Send className="size-4" />승인·발송</Button>}{selected.responseSentAt && <StatusPill tone="green">{selected.responseApprovedBy} 승인·발송</StatusPill>}</div></SectionCard>}
      </div>
    </> : <CustomerVocView tickets={state.vocTickets} onRate={(id, rating) => updateTicket(id, { satisfaction: rating })} />}
  </div>;
}

function CustomerVocView({ tickets, onRate }: { tickets: VocTicket[]; onRate: (id: string, rating: number) => void }) {
  return <div><div className="mb-5 rounded-lg border bg-card px-5 py-4"><p className="text-xs text-muted-foreground">고객사 포털</p><div className="mt-1 flex items-center justify-between"><div><h2 className="text-lg font-bold">한국스마트물류 운영 요청</h2><p className="text-xs text-muted-foreground">처리 상태와 완료 결과만 제공됩니다.</p></div><span className="flex items-center gap-1 text-xs text-[var(--success)]"><ShieldCheck className="size-4" />내부 원가·개인정보 비공개</span></div></div><div className="space-y-3">{tickets.filter(t => t.client === "한국스마트물류").map(t => <div key={t.id} className="rounded-lg border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs text-muted-foreground">{t.id} · {fmt(t.receivedAt)}</span><h3 className="mt-1 font-semibold">{t.title}</h3></div><StatusPill tone={t.status === "종료" ? "green" : t.status === "고객 확인" ? "blue" : "amber"}>{t.status}</StatusPill></div><div className="mt-4 flex items-center">{statusOrder.slice(0,5).map((s,i) => { const done = statusOrder.indexOf(t.status) >= i; return <div key={s} className="flex flex-1 items-center last:flex-none"><div className={`grid size-6 place-items-center rounded-full text-[10px] font-bold ${done ? "bg-[var(--brand-navy)] text-white" : "bg-muted text-muted-foreground"}`}>{done ? <Check className="size-3" /> : i+1}</div>{i < 4 && <div className={`h-px flex-1 ${done ? "bg-[var(--brand-navy)]" : "bg-border"}`} />}</div>})}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground">{statusOrder.slice(0,5).map(s => <span key={s}>{s}</span>)}</div>{t.responseDraft && <div className="mt-4 rounded bg-muted/50 p-3 text-sm leading-6"><b className="text-xs">처리 결과</b><p>{t.responseDraft}</p></div>}{t.status === "종료" && <div className="mt-4 flex items-center gap-2 border-t pt-3 text-xs"><span>처리 만족도</span>{[1,2,3,4,5].map(n => <button key={n} onClick={() => onRate(t.id,n)} className={`text-lg ${n <= (t.satisfaction ?? 0) ? "text-amber-500" : "text-muted"}`}>★</button>)}</div>}</div>)}</div></div>;
}
